# Alpine distro of 16 version of Node is more secure, efficient and lightweight
# Built for linux/amd64 architecture (x86_64)
FROM --platform=linux/amd64 node:16-alpine

# Set working directory
WORKDIR /usr/src

# Create verdi_front user and give permissions
RUN adduser --disabled-password verdi_front \
    && chown -R verdi_front ./ \
    # Clean yarn cache for better modules installation
    && yarn cache clean --force

USER verdi_front

RUN apk add --no-cache bash curl && curl -1sLf \
    'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.alpine.sh' | bash \
    && apk add infisical


# Copy project files
COPY ./.next ./.next
COPY ./package.json ./package.json
COPY ./next.config.js ./next.config.js
COPY ./.env.production ./.env.production

# Run app
CMD ["infisical", "run", "--env=front", "--", "yarn serve:prod"]