# Alpine distro of 16 version of Node is more secure, efficient and lightweight
# Built for linux/amd64 architecture (x86_64)
FROM --platform=linux/amd64 node:16-alpine

# Set working directory
WORKDIR /usr/src

RUN apk add --no-cache bash curl
RUN curl -1sLf \
    'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.alpine.sh' \
    | bash

RUN apk update && apk add infisical
RUN yarn cache clean --force

# Copy project files
COPY ./.next ./.next
COPY ./package.json ./package.json
COPY ./next.config.js ./next.config.js
COPY ./.env.production ./.env.production

# Run app
CMD ["infisical", "run", "--env=front", "--command", "yarn serve:prod"]