// export { VerdiLogo } from './VerdiLogo';

// Icons Folder ( para las carpetas)
export { RolledCarpetLarge } from './icons-Folder/RolledCarpetLarge'
export { CarpetLarge } from './icons-Folder/CarpetLarge'
export { CurtainLarge } from './icons-Folder/CurtainLarge'
export { RolledCurtainLarge } from './icons-Folder/RolledCurtainLarge'
export { ClothLarge } from './icons-Folder/ClothLarge'
export { HammockLarge } from './icons-Folder/HammockLarge'
export { SpiralLarge } from './icons-Folder/SpiralLarge'
export { SpiralAndWiresLarge } from './icons-Folder/SpiralAndWiresLarge'
export { HouseLarge } from './icons-Folder/HouseLarge'
export { BasketLarge } from './icons-Folder/BasketLarge'
export { KnittingLarge } from './icons-Folder/KnittingLarge'
export { ThreadLarge } from './icons-Folder/ThreadLarge'
export { PurseLarge } from './icons-Folder/PurseLarge'
export { DottedCookieLarge } from './icons-Folder/DottedCookieLarge'  
export { PillowLarge } from './icons-Folder/PillowLarge'
export { TowelLarge } from './icons-Folder/TowelLarge'
export { BagHeader } from './icons-Folder/BagHeader'
export { Lupe } from './icons-Folder/Lupe'

//Icons Small

export { Sofa } from './icons-Small/Sofa'
export { RolledCarpet } from './icons-Small/RolledCarpet'
export { Carpet } from './icons-Small/Carpet'
export { Curtain } from './icons-Small/Curtain'
export { Portrait } from './icons-Small/Portrait'
export { EmptyBox } from './icons-Small/EmptyBox'
export { ChekedBox } from './icons-Small/ChekedBox'
export { Bricks } from './icons-Small/Bricks'
export { SearchIcon } from './icons-Small/SearchIcon'
export { Bag } from './icons-Small/Bag'
export { Person } from './icons-Small/Person'
export { ShareIcon } from './icons-Small/ShareIcon'
export { Purse } from './icons-Small/Purse'
export { FilterIcon } from './icons-Small/FilterIcon'
export { PlusIcon } from './icons-Small/PlusIcon'
export { Mail } from './icons-Small/Mail'
export { Heart } from './icons-Small/Heart'
export { LeftArrow } from './icons-Small/LeftArrow'
export { RightArrow } from './icons-Small/RightArrow'
export { Suitcase } from './icons-Small/Suitcase'
export { TrashCan } from './icons-Small/TrashCan'
export { MinusIcon } from './icons-Small/MinusIcon'
export { FacebookIcon } from './icons-Small/FacebookIcon'
export { TwitterIcon } from './icons-Small/TwitterIcon'
export { InstagramIcon } from './icons-Small/InstagramIcon'
export { ListIcon } from './icons-Small/ListIcon'
export { DownArrow } from './icons-Small/DownArrow'
export { UpArrow } from './icons-Small/UpArrow'
export { ArrowForward} from './icons-Small/ArrowForward'
export { ArrowUp } from './icons-Small/ArrowUp'
export { ArrowDown } from './icons-Small/ArrowDown'
export { Close } from './icons-Small/Close'
export { ArrowBackward } from './icons-Small/ArrowBackward'

//Extra Icons

export { AddIconBlack } from './extra-icons/AddIconBlack'
export { AddIconWhite } from './extra-icons/AddIconWhite'
export { HeartFilled } from './extra-icons/FilledHeart'
export { Star } from './extra-icons/Star'
export { StarFilled } from './extra-icons/FilledStar'
export { RightArrowCircle } from './extra-icons/RightArrowCircle'
export { LeftArrowCircle } from './extra-icons/LeftArrowCircle'
export { CrossBoxLarge } from './extra-icons/CrossBoxLarge'
export { TickBoxLarge } from './extra-icons/TickBoxLarge'
export { SadFace } from './extra-icons/SadFace'
export { Home } from './extra-icons/Home'
export { HandAccess } from './extra-icons/HandAccess'
export { Camera } from './extra-icons/Camera'
export { Galery } from './extra-icons/Galery'
export { Upload } from './extra-icons/Upload'
export { SignOut } from './extra-icons/SignOut'
export { Download } from './extra-icons/Download'
export { Metrics } from './extra-icons/Metrics'
export {  CotizationList } from './extra-icons/CotizationList'
export {  Profile } from './extra-icons/Profile'
export { ThreeDots } from './extra-icons/ThreeDots'
